[package]
name = "voxel_game"
version = "0.1.0"
edition = "2024"

[dependencies]
gui = { path = "../gui" }
bevy_ecs = "0.16.0"
macroquad = "0.4"
noise = "0.9"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
once_cell = "1.19.0"
